{% set name = "zc.lockfile" %}
{% set version = "1.3.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "96cb13769e042988ea25d23d44cf09342ea0f887083d0f9736968f3617665853" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools

test:
  imports:
    - zc
    - zc.lockfile

about:
  home: https://github.com/zopefoundation/zc.lockfile
  license: ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Basic inter-process locks'
  dev_url: https://github.com/zopefoundation/zc.lockfile

extra:
  recipe-maintainers:
    - pmlandwehr
