{% set name = "zc.lockfile" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95a8e3846937ab2991b61703d6e0251d5abb9604e18412e2714e1b90db173253

build:
  preserve_egg_dir: True
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools

test:
  imports:
    - zc
    - zc.lockfile

about:
  home: https://github.com/zopefoundation/zc.lockfile
  license: ZPL 2.1
  license_file: LICENSE.txt
  license_family: Other
  summary: 'Basic inter-process locks'
  dev_url: https://github.com/zopefoundation/zc.lockfile

extra:
  recipe-maintainers:
    - pmlandwehr
