{% set name = "zc.lockfile" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zopefoundation/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9def32a8a78d7396d7ce2f33e109b9a4627ec236c0318daf7c806ee31370b957

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=78.1.1
  run:
    - python
    - setuptools

# Unable to run tests, zope.testing is not in the main channel.
test:
  imports:
    - zc
    - zc.lockfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/zc.lockfile
  summary: Basic inter-process locks
  license: ZPL-2.1
  license_file: LICENSE.txt
  license_family: Other
  description: |
    The zc.lockfile package provides a basic portable implementation of interprocess locks using lock files.
    The purpose if not specifically to lock files, but to simply provide locks with an implementation based
    on file-locking primitives. Of course, these locks could be used to mediate access to other files.
    For example, the ZODB file storage implementation uses file locks to mediate access to file-storage
    database files. The database files and lock file files are separate files.
  dev_url: https://github.com/zopefoundation/zc.lockfile
  doc_url: https://github.com/zopefoundation/zc.lockfile/blob/master/README.rst

extra:
  recipe-maintainers:
    - pmlandwehr
  skip-lints:
    - python_build_tool_in_run
