travis:
  secure:
    BINSTAR_TOKEN: CGl7hmy3I8rebQWiFT29Reij9rJjrmGowpBubmdniPHlnfd7nxw/zNgVnauT0iDC1QxU2aF8txVUpNR/t8181gvVl1ioSLsf2GbyulSE201mDlMw5zvfZYu/tDJGUoLUrpES4lLvdAFF6SZXzfOxYkZVR/5StUP7GhoL4wMihwi6TI/Ywgh5dvq0BHrbhZMimeVZRqMJAygmMA7VrWQ81racQfGl0qr/G7Ac6WRsKw9IhtEQRKHRkb+i6dXogyPH+BAc5LTaVy9I56ddSka0eVV2BpddJeo5O4j/97Wb0uhRhFmhxGoEDp5YZ3YCyArC/TuOUIELT9RMnbZlVHwY40+0uKExKyoo/tdULWI0C63KFGR9v/sUbX8dE7D8L4KBTaHoEhWgCB9mGjBe3MAXxtx/F11Y4cGMy69ED0nfk8bqIftFXJvbpbRp0P8E0Th9/5SfIbXj/yR9Vc1TKoURSQ71zMmyLROAJDCOprcv10+9X+po68CPC8ZwjjP9k5ZPx1SdQe+xGnIxM6noGz0fEj37b2LG+QQe9D9RhTIgx94Ewv8QHrClmqrOf0kmgbttaMKKU10hhvJYmMojFPCq/pfl/4fn3DkP+022J78ImPYHPZ4J/EbZa/1A4rtfzBzQzo2yRZZ1Hm/LmU4CsKWBOOn7I5qtqdbgkQMAgW76ItE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
