travis:
  secure:
    BINSTAR_TOKEN: Ba2FXb6HRqqnsfXlmVhlesi6EXmyAdOMhPBA+007PXk2alLXDuba2300SlKFJM1lpO8oenX9DKisz6oaUuuxnMtlwbjO41X5AnO7U0NyYY8r7JwABdDjIURmXbziWKXxyh+d0E2/r8OZu4CxSrWCvIKM0MVVBEHITmxQhSTRhUbR7hdAlMBcf0zjnBRkmdmqcjeLs+kKzcAUAblLk6AEi+uNVcIN9P1AgoDqRyhPuTQKFpwbxK+ltJy/4kdqQTaUDJ6fiVRXCg/2HHI9WHdoxBIjj1kXxVKN73JnMMmm4jSvU4F1S8ASVqhlqzzIgr6l3oM6QxG6fo0g3Kbk0KnyIl2PRSKexxyuH6DiEJFcByKFPS5z5q6K6gvPLi4KgECNKUZ1DvaUZzFoqhUyE2zEY5xbvAFUik2OgALMdVexIP0DQrYVpFsh+lpzao4Qwp8IaBbDLqLA6FXRbYZ/ntJMl4TbHUplma2o4KK8w1dDSe6bRvPR/HFGsqo8DeNqBBmtQSl5+xSw1UfDhk7UpuewcSEpDXkz4neioW/hHOhIrGouPXClaqDUmUN1UnrtNc2xB+z8QwsjheP6KQv/7QhatLlMdV4b4U27ZuHdG0YUpJNJx2Y35XzUJR3WBvIjqy6At8CIZCfdboR/FDfn8twPpwv782x0HUT2j+YFx86hS6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
